const ADD_ON_NAME_FIELD = "name";
const ADD_ON_VERSION_FIELD = "version";
const ADD_ON_NAME = "S6 TOOL BOX";
const ADD_ON_METADATA_VERSION = "1.1";
const ADD_ON_METADATA_VERSION_2 = "2.0";
const ADD_ON_RELEASE = "2.15.0, 13 JUNE 2024";
const CACHE_VERSION = "cache.version";


const META_DATA = {
  VALUE_FROM_FOLDER: "YES",
  VALUE_FROM_PARENT_FOLDER: "PARENT",
  NOT_VALUE_FROM_FOLDER: "NO"
}



